<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{a006fe57-da36-4aba-b269-66eb17a3ab15}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Counter: INT;
	
	Safety_Reset AT %Q*:BOOL;
	Safety_Run AT %Q*:BOOL :=TRUE;
	Safety_ErroAck AT %Q*:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Counter:=Counter+1;


Safety_BckpRstr();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="15" Count="1" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>